server:
  port: 9527
spring:
  application:
    name: gatewayServer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: security_routh1  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://SECURITYSERVER
          predicates:
            - Path=/oauth/**
        - id: blog_routh1
          uri: lb://BLOGSERVER
          predicates:
            - Path=/account/**,/blog/**,/user/**,/role/**,/permission/**,/relationUserAndRole/**,/relationRoleAndPermission/**,/systemLog/**
        - id: oss_routh1
          uri: lb://OSSSERVER
          predicates:
            - Path=/oss/**

# 注册进 eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
